# Generated by Django 5.1.2 on 2026-02-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('full_address', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=55, null=True)),
                ('aadhar_image', models.FileField(max_length=255, upload_to='userDocuments')),
                ('pancard_image', models.FileField(max_length=255, upload_to='userDocuments')),
                ('live_photo', models.FileField(max_length=255, upload_to='userDocuments')),
                ('requested_amount', models.CharField(blank=True, max_length=25, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('what_you_do', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_salary', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
