# Generated by Django 5.1.15 on 2026-02-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='spouse_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
