# Generated by Django 5.1.15 on 2026-02-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_spouse_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_agent_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('system', 'System')], db_index=True, max_length=10)),
                ('sender_label', models.CharField(blank=True, default='', max_length=120)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('media', 'Media')], db_index=True, default='text', max_length=10)),
                ('content', models.TextField(blank=True, default='')),
                ('media_file', models.FileField(blank=True, max_length=255, null=True, upload_to='chatMedia')),
                ('media_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_by_user', models.BooleanField(default=False)),
                ('read_by_agent', models.BooleanField(default=False)),
                ('deleted_for_everyone', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by_agent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [
                    models.Index(fields=['user', 'created_at'], name='chat_usr_created_idx'),
                    models.Index(fields=['user', 'deleted_for_everyone', 'created_at'], name='chat_usr_delcrt_idx'),
                    models.Index(fields=['user', 'sender_role', 'read_by_agent'], name='chat_usr_ragent_idx'),
                    models.Index(fields=['user', 'sender_role', 'read_by_user'], name='chat_usr_ruser_idx'),
                ],
            },
        ),
    ]
