# Generated by Django 5.1.15 on 2026-02-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customuser_chat_fields_and_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.FileField(max_length=255, upload_to='globalPaymentQr')),
                ('account_holder_name', models.CharField(max_length=120)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=80)),
                ('ifsc', models.CharField(max_length=20)),
                ('branch', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_global_payment_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['is_active', 'expires_at'], name='gp_active_exp_idx'),
                    models.Index(fields=['created_at'], name='gp_created_idx'),
                ],
            },
        ),
    ]
