# Generated by Django 5.1.15 on 2026-02-25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_globalpaymentconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.PositiveSmallIntegerField(db_index=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['question_id'],
                'indexes': [models.Index(fields=['is_active', 'question_id'], name='agrq_active_qid_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgreementAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='myapp.agreementquestion')),
                ('user', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['question__question_id'],
                'indexes': [
                    models.Index(fields=['user', 'question'], name='agra_user_q_idx'),
                    models.Index(fields=['user', 'answered_at'], name='agra_user_ansat_idx')
                ],
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='unique_user_agreement_answer')],
            },
        ),
    ]
