# Generated by Django 5.1.15 on 2026-02-25 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_agreementquestion_agreementanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_chat_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='globalpaymentconfig',
            name='account_holder_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='globalpaymentconfig',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='globalpaymentconfig',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='globalpaymentconfig',
            name='ifsc',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='globalpaymentconfig',
            name='qr_image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='globalPaymentQr'),
        ),
        migrations.CreateModel(
            name='PaymentConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.FileField(blank=True, max_length=255, null=True, upload_to='paymentTemplates')),
                ('account_holder_name', models.CharField(blank=True, default='', max_length=120)),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('account_number', models.CharField(blank=True, default='', max_length=80)),
                ('ifsc', models.CharField(blank=True, default='', max_length=20)),
                ('branch', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='pt_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=120)),
                ('proof_image', models.FileField(max_length=255, upload_to='paymentProofs')),
                ('amount_inr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_set_id', models.CharField(blank=True, default='', max_length=80)),
                ('payment_scope', models.CharField(blank=True, choices=[('global', 'Global'), ('user', 'User')], default='', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='ptxn_status_created_idx'), models.Index(fields=['user', 'created_at'], name='ptxn_user_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'transaction_id'), name='uniq_user_txn_id')],
            },
        ),
    ]
