# Generated by Django 5.1.15 on 2026-02-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customuser_is_chat_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agreement_completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='agreement_consent_video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='agreementMedia/videos'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='agreement_signature',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='agreementMedia/signatures'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='agreement_tab_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
