# Generated by Django 5.1.15 on 2026-02-25 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customuser_agreement_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=80, unique=True)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=400)),
                ('short_bio', models.CharField(blank=True, default='', max_length=180)),
                ('tone_guidelines', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'display_name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='persona_active_sort_idx')],
            },
        ),
        migrations.CreateModel(
            name='GhostChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_persona_locked', models.BooleanField(db_index=True, default=True)),
                ('is_favorite', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ghost_threads', to='myapp.communitypersona')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ghost_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GhostChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('system', 'System')], db_index=True, max_length=10)),
                ('sender_label', models.CharField(blank=True, default='', max_length=120)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('media', 'Media')], db_index=True, default='text', max_length=10)),
                ('content', models.TextField(blank=True, default='')),
                ('content_masked', models.BooleanField(db_index=True, default=False)),
                ('moderation_note', models.CharField(blank=True, default='', max_length=255)),
                ('media_file', models.FileField(blank=True, max_length=255, null=True, upload_to='ghostChatMedia')),
                ('media_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_by_user', models.BooleanField(default=False)),
                ('read_by_agent', models.BooleanField(default=False)),
                ('deleted_for_everyone', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by_agent', models.BooleanField(default=False)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.ghostchatthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('community', 'Community'), ('private_chat', 'Private Chat')], db_index=True, max_length=20)),
                ('action', models.CharField(choices=[('masked', 'Masked'), ('blocked', 'Blocked'), ('warned', 'Warned')], db_index=True, max_length=20)),
                ('reason', models.CharField(max_length=255)),
                ('channel_ref', models.CharField(blank=True, default='', max_length=120)),
                ('original_excerpt', models.TextField(blank=True, default='')),
                ('sanitized_excerpt', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('user', 'User'), ('persona', 'Persona')], db_index=True, max_length=12)),
                ('content', models.TextField()),
                ('content_masked', models.BooleanField(db_index=True, default=False)),
                ('moderation_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.communitypost')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='myapp.communitypersona')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parent', 'created_at'], name='cpost_parent_created_idx'), models.Index(fields=['author_type', 'created_at'], name='cpost_author_created_idx'), models.Index(fields=['is_deleted', 'created_at'], name='cpost_deleted_created_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ghostchatthread',
            index=models.Index(fields=['user', 'last_message_at'], name='gthread_user_lastmsg_idx'),
        ),
        migrations.AddIndex(
            model_name='ghostchatthread',
            index=models.Index(fields=['is_favorite', 'last_message_at'], name='gthread_fav_lastmsg_idx'),
        ),
        migrations.AddIndex(
            model_name='ghostchatthread',
            index=models.Index(fields=['persona', 'last_message_at'], name='gthread_persona_lastmsg_idx'),
        ),
        migrations.AddConstraint(
            model_name='ghostchatthread',
            constraint=models.UniqueConstraint(fields=('user', 'persona'), name='uniq_user_persona_ghost_thread'),
        ),
        migrations.AddIndex(
            model_name='ghostchatmessage',
            index=models.Index(fields=['thread', 'created_at'], name='gmsg_thread_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ghostchatmessage',
            index=models.Index(fields=['thread', 'deleted_for_everyone', 'created_at'], name='gmsg_thread_delcrt_idx'),
        ),
        migrations.AddIndex(
            model_name='ghostchatmessage',
            index=models.Index(fields=['thread', 'sender_role', 'read_by_agent'], name='gmsg_thread_ragent_idx'),
        ),
        migrations.AddIndex(
            model_name='ghostchatmessage',
            index=models.Index(fields=['thread', 'sender_role', 'read_by_user'], name='gmsg_thread_ruser_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationevent',
            index=models.Index(fields=['context', 'created_at'], name='mod_context_created_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationevent',
            index=models.Index(fields=['user', 'created_at'], name='mod_user_created_idx'),
        ),
    ]
