# Generated by Django 5.1.15 on 2026-02-25 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_communitypersona_ghostchatthread_ghostchatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='media_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='communityMedia'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='media_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='CommunitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_title', models.CharField(blank=True, default='community chat.', max_length=120)),
                ('active_members_display', models.PositiveIntegerField(db_index=True, default=89)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_community_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
