# Generated by Django 5.1.15 on 2026-02-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_communitypost_media_file_communitypost_media_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypersona',
            name='ghost_id',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='communitypersona',
            name='identity_tag',
            field=models.CharField(blank=True, default='general', max_length=80),
        ),
        migrations.AddField(
            model_name='communitypersona',
            name='info',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
    ]
