# Generated by Django 5.1.15 on 2026-02-26 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_communitypersona_ghost_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GLOBAL', 'Global'), ('PRIVATE', 'Private')], db_index=True, max_length=10)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('cta_text', models.CharField(max_length=80)),
                ('priority_label', models.CharField(blank=True, default='IMPORTANT', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'type', 'created_at'], name='ann_active_type_created_idx'), models.Index(fields=['is_active', 'target_user', 'created_at'], name='ann_active_user_created_idx')],
            },
        ),
    ]
